//! Codec matrix (W-006): every supported container decodes to real playback,
//! and corrupt input fails loudly without taking anything down.
//!
//! Fixtures are generated by `scripts/generate-fixtures.sh` (short synthetic
//! tones, committed) and shared from `tests/fixtures/`. Playback runs against
//! `fakesink`: real decode pipelines, no sound server, silent and fast.

use std::{path::PathBuf, time::Duration};

use tokio::sync::mpsc;
use tunex_core::PlayerEvent;
use tunex_player::PlayerEngine;

/// Fixture path shared from the workspace `tests/fixtures/` directory.
fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures")
        .join(name)
}

/// Engine wired to `fakesink`: full pipeline behavior, no sound server.
fn test_engine() -> (PlayerEngine, mpsc::Receiver<PlayerEvent>) {
    let (events, receiver) = mpsc::channel(PlayerEngine::event_buffer());
    let engine = PlayerEngine::new(events).expect("engine builds");
    let sink = gstreamer::ElementFactory::make("fakesink")
        .build()
        .expect("fakesink exists");
    engine.set_audio_sink(&sink);
    (engine, receiver)
}

/// Next event or a named failure after a grace period.
async fn next_event(receiver: &mut mpsc::Receiver<PlayerEvent>, what: &str) -> PlayerEvent {
    tokio::time::timeout(Duration::from_secs(10), receiver.recv())
        .await
        .unwrap_or_else(|_| panic!("{what}: event arrives in time"))
        .expect("sender lives as long as the engine")
}

/// Play one fixture file to the `Playing` state with a known duration.
async fn play_fixture(name: &str) {
    let (engine, mut receiver) = test_engine();
    engine
        .load_path(&fixture(name))
        .unwrap_or_else(|err| panic!("{name}: load works: {err}"));
    engine
        .play()
        .unwrap_or_else(|err| panic!("{name}: play works: {err}"));
    loop {
        match next_event(&mut receiver, name).await {
            PlayerEvent::StateChanged(tunex_core::PlaybackState::Playing) => break,
            PlayerEvent::PlaybackError(message) => {
                panic!("{name}: decodes without errors, got: {message}");
            }
            _ => {}
        }
    }
    assert!(
        engine.duration().is_some(),
        "{name}: container exposes a duration"
    );
    engine.stop().expect("stop works");
}

#[tokio::test]
async fn wav_decodes_to_playback() {
    play_fixture("sine.wav").await;
}

#[tokio::test]
async fn flac_decodes_to_playback() {
    play_fixture("sine.flac").await;
}

#[tokio::test]
async fn ogg_vorbis_decodes_to_playback() {
    play_fixture("sine.ogg").await;
}

#[tokio::test]
async fn opus_decodes_to_playback() {
    play_fixture("sine.opus").await;
}

#[tokio::test]
async fn mp3_decodes_to_playback() {
    play_fixture("sine.mp3").await;
}

#[tokio::test]
async fn m4a_aac_decodes_to_playback() {
    play_fixture("sine.m4a").await;
}

#[tokio::test]
async fn corrupt_file_fails_loudly_and_survives() {
    let (engine, mut receiver) = test_engine();
    engine
        .load_path(&fixture("corrupt.mp3"))
        .expect("load only stages the URI");
    if engine.play().is_err() {
        return;
    }
    loop {
        match next_event(&mut receiver, "corrupt.mp3").await {
            PlayerEvent::PlaybackError(_) => break,
            PlayerEvent::EndOfTrack => {
                panic!("corrupt input must error, never cleanly end");
            }
            _ => {}
        }
    }
    // The engine is still usable afterwards: the app survives corrupt input.
    engine.stop().expect("stop works after corrupt input");
    assert_eq!(engine.state(), tunex_core::PlaybackState::Stopped);
}
